# mode should be same case (upper/lower) = {LBP, HSV, EDGE}
# Features = {BinaryCountFeature, BinaryDistributioinFeature}

[BinaryCountFeature]
enabled = true
[BinaryCountFeature.ObjectDetection]
enabled = true            
mode = HSV            
noisethreshold = 200
[BinaryCountFeature.PreProcessing]
enabled = true            
mode = EDGE
noisethreshold = 0

[BinaryDistributionFeature]
enabled = true
[BinaryDistributionFeature.ObjectDetection]
enabled = true            
mode = HSV            
noisethreshold = 200
[BinaryDistributionFeature.PreProcessing]
enabled = true            
mode = EDGE
noisethreshold = 0

[ImageViewer]
enabled = true
[ImageViewer.ObjectDetection]
enabled = true            
mode = HSV            
noisethreshold = 200
[ImageViewer.PreProcessing]
enabled = true            
mode = EDGE
noisethreshold = 0
