##################################################################
# configuration.ini
# This file contains the pre-processing configuration for this application
# Note:
#   - mode should be same case (upper/lower) = {LBP, HSV, EDGE}
#   - Features = {BinaryCountFeature, BinaryDistributioinFeature}
##################################################################

# Configuration applied when training or evaluating data
[BinaryCountFeature]
enabled = true
[BinaryCountFeature.ObjectDetection]
enabled = true            
mode = HSV            
noiseThreshold = 200
[BinaryCountFeature.PreProcessing]
enabled = true            
mode = EDGE
noiseThreshold = 0

[BinaryDistributionFeature]
enabled = true
[BinaryDistributionFeature.ObjectDetection]
enabled = true            
mode = HSV            
noiseThreshold = 200
[BinaryDistributionFeature.PreProcessing]
enabled = true            
mode = EDGE
noiseThreshold = 0

# Configuration applied when manually inspecting an image with view
[ImageViewer]
enabled = true
[ImageViewer.ObjectDetection]
enabled = true            
mode = HSV            
noiseThreshold = 200
[ImageViewer.PreProcessing]
enabled = true            
mode = EDGE
noiseThreshold = 0
